import { combineReducers } from "redux";
import { reducers } from "./reducers";
const projReducers = combineReducers({
 showSendAlert:reducers,
 showSettings:reducers,
 showHelp:reducers,
 showNotes:reducers,
 showFind: reducers ,
 showIssues: reducers,
 showDemo: reducers,
 showFiles: reducers,
 showActiveFeed: reducers,
 loadShowDemoFeed: reducers,
 showConnect: reducers,
 showDelete: reducers,
 showSendMessage: reducers,
 selectedFeed:reducers,
 newCase:reducers,
 pageNo:reducers,
 timeCode:reducers,
 annotation:reducers,
 autoSplit:reducers,
 enableDemo:reducers,
 enableFiles:reducers,
 enableFind:reducers,
 enableHelp:reducers,
 enableIndex:reducers,
 enableIssues:reducers,
 enableKeyword:reducers,
 enableRemote:reducers,
 enableSend:reducers,
 enableSettings:reducers,
 enableSidebar:reducers,
 enableVerbose:reducers,
 enableZoom:reducers,
 words:reducers,
 annotationList:reducers,
 annotationUpdated:reducers
})
export default projReducers;